/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `perfume` WRITE;
/*!40000 ALTER TABLE `perfume` DISABLE KEYS */;
INSERT INTO `perfume` (`id`, `brand`, `confidence`, `gender`, `image_url`, `name`, `release_year`, `sillage`, `line`, `description`, `notes`, `accords`, `season`, `occasion`, `rating`, `review_count`) VALUES
(1,'Dior','low','women','https://cdn.fragella.com/images/dior-dior-dior-for-women.jpg','Dior Dior Dior for women',1976,'Strong','Dior Dior','A fresh, citrus, aromatic composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]','{"Spring":0.6,"Summer":0.9,"Autumn":0.45,"Winter":0.3}','{"Daily":0.85,"Office":0.75,"Evening":0.58,"Special":0.63}',3.9,117),
(2,'Dior','low','women','https://cdn.fragella.com/images/dior-me,-dior-me-not-dior-for-women.jpg','Dior Me, Dior Me Not for women',2004,'Strong','Me, Dior Me Not','A woody, powdery, smoky composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.98,"Special":0.93}',4.0,154),
(3,'Dior','low','women','https://cdn.fragella.com/images/lily-dior-dior-for-women.jpg','Lily Dior for women',2004,'Moderate','Lily Dior','A floral, sweet, powdery composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.8,"Special":0.85}',4.1,191),
(4,'Dior','high','women','https://cdn.fragella.com/images/miss-dior-dior-for-women.jpg','Miss Dior for women',1947,'Strong','Miss Dior','A floral, sweet, powdery composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.88,"Special":0.93}',4.2,228),
(5,'Dior','medium','women','https://cdn.fragella.com/images/dior-grand-bal-dior-for-women.jpg','Dior Grand Bal for women',2012,'Strong','Grand Bal','A sweet, gourmand, vanilla composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Mandarin","Blackcurrant"],"middle":["Honey","Orange Blossom","Jasmine"],"base":["Vanilla","Tonka Bean","Patchouli"]}','["Sweet","Gourmand","Vanilla","Amber"]','{"Spring":0.5,"Summer":0.35,"Autumn":0.85,"Winter":0.9}','{"Daily":0.65,"Office":0.45,"Evening":0.96,"Special":0.98}',4.3,265),
(6,'Chanel','low','women','https://cdn.fragella.com/images/chanel-chance.jpg','Chanel Chance',2005,'Strong','Chance','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.88,"Special":0.93}',4.4,302),
(7,'Chanel','high','women','https://cdn.fragella.com/images/chanel-chance-eau-tendre.jpg','Chanel Chance Eau Tendre',2010,'Moderate','Chance Eau Tendre','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.8,"Special":0.85}',4.5,339),
(8,'Chanel','low','women','https://cdn.fragella.com/images/chanel-chance-eau-fraiche.jpg','Chanel Chance Eau Fraiche',2007,'Moderate','Chance Eau Fraiche','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.8,"Special":0.85}',4.6,376),
(9,'Chanel','low','women','https://cdn.fragella.com/images/chanel-chance-eau-vive.jpg','Chanel Chance Eau Vive',2015,'Moderate','Chance Eau Vive','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.8,"Special":0.85}',4.7,413),
(10,'Chanel','low','women','https://cdn.fragella.com/images/chance-parfum-chanel-for-women.jpg','Chance Parfum for women',2003,'Strong','Chance Parfum','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.88,"Special":0.93}',4.8,450),
(11,'Yves Saint Laurent','high','men','https://cdn.fragella.com/images/yves-saint-laurent-y-yves-saint-laurent-for-men.jpg','Yves Saint Laurent Y for men',2017,'Moderate','Y','A fresh, citrus, aromatic composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]','{"Spring":0.6,"Summer":0.9,"Autumn":0.45,"Winter":0.3}','{"Daily":0.85,"Office":0.75,"Evening":0.5,"Special":0.55}',4.9,487),
(12,'Yves Saint Laurent','high','women','https://cdn.fragella.com/images/manifesto-yves-saint-laurent.jpg','Manifesto Yves Saint Laurent',2012,'Strong','Manifesto Yves','A oriental, spicy, warm composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]','{"Spring":0.4,"Summer":0.25,"Autumn":0.8,"Winter":0.95}','{"Daily":0.45,"Office":0.5,"Evening":0.98,"Special":0.98}',3.8,104),
(13,'Yves Saint Laurent','high','women','https://cdn.fragella.com/images/libre-yves-saint-laurent.jpg','Libre Yves Saint Laurent',2019,'Strong','Libre Yves','A oriental, spicy, warm composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]','{"Spring":0.4,"Summer":0.25,"Autumn":0.8,"Winter":0.95}','{"Daily":0.45,"Office":0.5,"Evening":0.98,"Special":0.98}',3.9,141),
(14,'Yves Saint Laurent','high','men','https://cdn.fragella.com/images/lhomme-yves-saint-laurent.jpg','L''Homme Yves Saint Laurent',2006,'Moderate','L''Homme Yves','A floral, sweet, powdery composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.8,"Special":0.85}',4.0,178),
(15,'Yves Saint Laurent','high','men','https://cdn.fragella.com/images/myslf-yves-saint-laurent.jpg','Myslf Yves Saint Laurent',2023,'Moderate','Myslf Yves','A floral, sweet, powdery composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.8,"Special":0.85}',4.1,215),
(16,'Tom Ford','high','Men','https://cdn.fragella.com/images/tom-ford-black-orchid.jpg','Tom Ford Black Orchid',2006,'Strong','Black Orchid','A floral, sweet, powdery composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.88,"Special":0.93}',4.2,252),
(17,'Tom Ford','high','Men','https://cdn.fragella.com/images/tom-ford-black-lacquer.jpg','Tom Ford Black Lacquer',0,'Moderate','Black Lacquer','A oriental, spicy, warm composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]','{"Spring":0.4,"Summer":0.25,"Autumn":0.8,"Winter":0.95}','{"Daily":0.45,"Office":0.5,"Evening":0.92,"Special":0.9}',4.3,289),
(18,'Tom Ford','high','Men','https://cdn.fragella.com/images/tom-ford-ombre-leather.jpg','Tom Ford Ombre Leather',2018,'Strong','Ombre Leather','A woody, powdery, smoky composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.98,"Special":0.93}',4.4,326),
(19,'Tom Ford','high','Men','https://cdn.fragella.com/images/tom-ford-velvet-orchid.jpg','Tom Ford Velvet Orchid',2014,'Strong','Velvet Orchid','A floral, sweet, powdery composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.88,"Special":0.93}',4.5,363),
(20,'Tom Ford','high','Men','https://cdn.fragella.com/images/tom-ford-oud-wood.jpg','Tom Ford Oud Wood',2007,'Moderate','Oud Wood','A oriental, spicy, warm composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]','{"Spring":0.4,"Summer":0.25,"Autumn":0.8,"Winter":0.95}','{"Daily":0.45,"Office":0.5,"Evening":0.92,"Special":0.9}',4.6,400),
(21,'Versace','medium','women','https://cdn.fragella.com/images/gianni-versace-versace-for-women.jpg','Gianni Versace for women',1981,'Strong','Gianni Versace','A fresh, citrus, aromatic composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]','{"Spring":0.6,"Summer":0.9,"Autumn":0.45,"Winter":0.3}','{"Daily":0.85,"Office":0.75,"Evening":0.58,"Special":0.63}',4.7,437),
(22,'Versace','low','men','https://cdn.fragella.com/images/versace-man-versace-for-men.jpg','Versace Man for men',2003,'Strong','Man','A fresh, citrus, aromatic composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]','{"Spring":0.6,"Summer":0.9,"Autumn":0.45,"Winter":0.3}','{"Daily":0.85,"Office":0.75,"Evening":0.58,"Special":0.63}',4.8,474),
(23,'Versace','low','women','https://cdn.fragella.com/images/versace-woman-summer-versace-for-women.jpg','Versace Woman Summer for women',2002,'Moderate','Woman Summer','A fresh, citrus, aromatic composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]','{"Spring":0.6,"Summer":0.9,"Autumn":0.45,"Winter":0.3}','{"Daily":0.85,"Office":0.75,"Evening":0.5,"Special":0.55}',4.9,91),
(24,'Versace','low','women','https://cdn.fragella.com/images/versace-essence-ethereal-versace-for-women.jpg','Versace Essence Ethereal for women',2000,'Moderate','Essence Ethereal','A fresh, citrus, aromatic composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]','{"Spring":0.6,"Summer":0.9,"Autumn":0.45,"Winter":0.3}','{"Daily":0.85,"Office":0.75,"Evening":0.5,"Special":0.55}',3.8,128),
(25,'Versace','low','women','https://cdn.fragella.com/images/versace-essence-emotional-versace-for-women.jpg','Versace Essence Emotional for women',2000,'Moderate','Essence Emotional','A sweet, gourmand, vanilla composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Mandarin","Blackcurrant"],"middle":["Honey","Orange Blossom","Jasmine"],"base":["Vanilla","Tonka Bean","Patchouli"]}','["Sweet","Gourmand","Vanilla","Amber"]','{"Spring":0.5,"Summer":0.35,"Autumn":0.85,"Winter":0.9}','{"Daily":0.65,"Office":0.45,"Evening":0.88,"Special":0.92}',3.9,165),
(26,'Giorgio Armani','high','men','https://cdn.fragella.com/images/giorgio-armani-variety.jpg','Giorgio Armani Variety',2004,'Strong','Variety','A woody, powdery, smoky composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.98,"Special":0.93}',4.0,202),
(27,'Giorgio Armani','high','women','https://cdn.fragella.com/images/armani-giorgio-armani-for-women.jpg','Armani for women',1981,'Strong','Signature','A woody, powdery, smoky composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.98,"Special":0.93}',4.1,239),
(28,'Giorgio Armani','high','men','https://cdn.fragella.com/images/armani-attitude-giorgio-armani-for-men.jpg','Armani Attitude for men',2007,'Moderate','Armani Attitude','A woody, powdery, smoky composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.95,"Special":0.85}',4.2,276),
(29,'Giorgio Armani','low','unisex','https://cdn.fragella.com/images/armani-prive-laque-giorgio-armani-unisex.jpg','Armani Prive Laque unisex',2019,'Strong','Armani Prive','A woody, powdery, smoky composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.98,"Special":0.93}',4.3,313),
(30,'Giorgio Armani','high','men','https://cdn.fragella.com/images/armani-mania-giorgio-armani-for-men.jpg','Armani Mania for men',2002,'Moderate','Armani Mania','A oriental, spicy, warm composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]','{"Spring":0.4,"Summer":0.25,"Autumn":0.8,"Winter":0.95}','{"Daily":0.45,"Office":0.5,"Evening":0.92,"Special":0.9}',4.4,350),
(31,'Creed','high','women','https://cdn.fragella.com/images/creed.jpg','Creed',2010,'Moderate','Signature','A woody, powdery, smoky composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.95,"Special":0.85}',4.5,387),
(32,'Creed','low','unisex','https://cdn.fragella.com/images/creed-pour-enfants-creed-unisex.jpg','Creed Pour Enfants unisex',2015,'Moderate','Pour Enfants','A woody, powdery, smoky composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.95,"Special":0.85}',4.6,424),
(33,'Creed','high','men','https://cdn.fragella.com/images/creed-viking.jpg','Creed Viking',2017,'Moderate','Viking','A woody, powdery, smoky composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.95,"Special":0.85}',4.7,461),
(34,'Creed','high','men','https://cdn.fragella.com/images/creed-erolfa.jpg','Creed Erolfa',1992,'Moderate','Erolfa','A fresh, citrus, aromatic composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]','{"Spring":0.6,"Summer":0.9,"Autumn":0.45,"Winter":0.3}','{"Daily":0.85,"Office":0.75,"Evening":0.5,"Special":0.55}',4.8,498),
(35,'Creed','high','men','https://cdn.fragella.com/images/creed-himalaya.jpg','Creed Himalaya',2002,'Moderate','Himalaya','A fresh, citrus, aromatic composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]','{"Spring":0.6,"Summer":0.9,"Autumn":0.45,"Winter":0.3}','{"Daily":0.85,"Office":0.75,"Evening":0.5,"Special":0.55}',4.9,115),
(36,'Jean Paul Gaultier','high','unisex','https://cdn.fragella.com/images/gaultier2-jean-paul-gaultier-unisex.jpg','Gaultier2 unisex',2022,'Moderate','Signature','A woody, powdery, smoky composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.95,"Special":0.85}',3.8,152),
(37,'Jean Paul Gaultier','high','men','https://cdn.fragella.com/images/jean-paul-gaultier.jpg','Jean Paul Gaultier',1995,'Strong','Jean Paul','A woody, powdery, smoky composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.98,"Special":0.93}',3.9,189),
(38,'Jean Paul Gaultier','low','women','https://cdn.fragella.com/images/jean-paul-gaultier-summer-jean-paul-gaultier-for-women.jpg','Jean Paul Gaultier Summer for women',1997,'Strong','Summer','A fresh, citrus, aromatic composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]','{"Spring":0.6,"Summer":0.9,"Autumn":0.45,"Winter":0.3}','{"Daily":0.85,"Office":0.75,"Evening":0.58,"Special":0.63}',4.0,226),
(39,'Jean Paul Gaultier','high','women','https://cdn.fragella.com/images/jean-paul-gaultier-divine.jpg','Jean Paul Gaultier Divine',2023,'Moderate','Divine','A floral, sweet, powdery composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.8,"Special":0.85}',4.1,263),
(40,'Jean Paul Gaultier','high','women','https://cdn.fragella.com/images/jean-paul-gaultier-scandal.jpg','Jean Paul Gaultier Scandal',2017,'Strong','Scandal','A oriental, spicy, warm composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]','{"Spring":0.4,"Summer":0.25,"Autumn":0.8,"Winter":0.95}','{"Daily":0.45,"Office":0.5,"Evening":0.98,"Special":0.98}',4.2,300),
(41,'Prada','high','men','https://cdn.fragella.com/images/prada.jpg','Prada',2004,'Strong','Signature','A woody, powdery, smoky composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.98,"Special":0.93}',4.3,337),
(42,'Prada','low','women','https://cdn.fragella.com/images/prada-prada-for-women.jpg','Prada Prada for women',1990,'Strong','Prada','A woody, powdery, smoky composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]','{"Spring":0.45,"Summer":0.2,"Autumn":0.95,"Winter":0.8}','{"Daily":0.55,"Office":0.7,"Evening":0.98,"Special":0.93}',4.4,374),
(43,'Prada','low','women','https://cdn.fragella.com/images/prada-tendre-prada-for-women.jpg','Prada Tendre for women',2006,'Strong','Tendre','A floral, sweet, powdery composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.88,"Special":0.93}',4.5,411),
(44,'Prada','low','women','https://cdn.fragella.com/images/prada-intense-prada-for-women.jpg','Prada Intense for women',2005,'Strong','Intense','A oriental, spicy, warm composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]','{"Spring":0.4,"Summer":0.25,"Autumn":0.8,"Winter":0.95}','{"Daily":0.45,"Office":0.5,"Evening":0.98,"Special":0.98}',4.6,448),
(45,'Prada','low','women','https://cdn.fragella.com/images/prada-les-infusion-de-prada.jpg','Prada Les Infusion De Prada',2022,'Moderate','Les Infusion De Prada','A floral, sweet, powdery composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]','{"Spring":0.75,"Summer":0.55,"Autumn":0.65,"Winter":0.45}','{"Daily":0.7,"Office":0.65,"Evening":0.8,"Special":0.85}',4.7,485);
/*!40000 ALTER TABLE `perfume` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
