/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `perfume` WRITE;
/*!40000 ALTER TABLE `perfume` DISABLE KEYS */;
INSERT INTO `perfume` (`id`, `brand`, `gender`, `image_url`, `name`, `release_year`, `sillage`, `line`, `description`, `notes`, `accords`) VALUES
(1,'Dior','women','https://cdn.fragella.com/images/dior-dior-dior-for-women.jpg','Dior Dior Dior for women',1976,'Strong','Dior Dior','A fresh, citrus, aromatic composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]'),
(2,'Dior','women','https://cdn.fragella.com/images/dior-me-dior-me-not-dior-for-women.jpg','Dior Me, Dior Me Not for women',2004,'Strong','Me, Dior Me Not','A woody, powdery, smoky composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(3,'Dior','women','https://cdn.fragella.com/images/lily-dior-dior-for-women.jpg','Lily Dior for women',2004,'Moderate','Lily Dior','A floral, sweet, powdery composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(4,'Dior','women','https://cdn.fragella.com/images/miss-dior-dior-for-women.jpg','Miss Dior for women',1947,'Strong','Miss Dior','A floral, sweet, powdery composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(5,'Dior','women','https://cdn.fragella.com/images/dior-grand-bal-dior-for-women.jpg','Dior Grand Bal for women',2012,'Strong','Grand Bal','A sweet, gourmand, vanilla composition by Dior. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Mandarin","Blackcurrant"],"middle":["Honey","Orange Blossom","Jasmine"],"base":["Vanilla","Tonka Bean","Patchouli"]}','["Sweet","Gourmand","Vanilla","Amber"]'),
(6,'Chanel','women','https://cdn.fragella.com/images/chanel-chance.jpg','Chanel Chance',2005,'Strong','Chance','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(7,'Chanel','women','https://cdn.fragella.com/images/chanel-chance-eau-tendre.jpg','Chanel Chance Eau Tendre',2010,'Moderate','Chance Eau Tendre','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(8,'Chanel','women','https://cdn.fragella.com/images/chanel-chance-eau-fraiche.jpg','Chanel Chance Eau Fraiche',2007,'Moderate','Chance Eau Fraiche','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(9,'Chanel','women','https://cdn.fragella.com/images/chanel-chance-eau-vive.jpg','Chanel Chance Eau Vive',2015,'Moderate','Chance Eau Vive','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(10,'Chanel','women','https://cdn.fragella.com/images/chance-parfum-chanel-for-women.jpg','Chance Parfum for women',2003,'Strong','Chance Parfum','A floral, sweet, powdery composition by Chanel. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(11,'Yves Saint Laurent','men','https://cdn.fragella.com/images/yves-saint-laurent-y-yves-saint-laurent-for-men.jpg','Yves Saint Laurent Y for men',2017,'Moderate','Y','A fresh, citrus, aromatic composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]'),
(12,'Yves Saint Laurent','women','https://cdn.fragella.com/images/manifesto-yves-saint-laurent.jpg','Manifesto Yves Saint Laurent',2012,'Strong','Manifesto Yves','A oriental, spicy, warm composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]'),
(13,'Yves Saint Laurent','women','https://cdn.fragella.com/images/libre-yves-saint-laurent.jpg','Libre Yves Saint Laurent',2019,'Strong','Libre Yves','A oriental, spicy, warm composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]'),
(14,'Yves Saint Laurent','men','https://cdn.fragella.com/images/lhomme-yves-saint-laurent.jpg','L''Homme Yves Saint Laurent',2006,'Moderate','L''Homme Yves','A floral, sweet, powdery composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(15,'Yves Saint Laurent','men','https://cdn.fragella.com/images/myslf-yves-saint-laurent.jpg','Myslf Yves Saint Laurent',2023,'Moderate','Myslf Yves','A floral, sweet, powdery composition by Yves Saint Laurent. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(16,'Tom Ford','Men','https://cdn.fragella.com/images/tom-ford-black-orchid.jpg','Tom Ford Black Orchid',2006,'Strong','Black Orchid','A floral, sweet, powdery composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(17,'Tom Ford','Men','https://cdn.fragella.com/images/tom-ford-black-lacquer.jpg','Tom Ford Black Lacquer',0,'Moderate','Black Lacquer','A oriental, spicy, warm composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]'),
(18,'Tom Ford','Men','https://cdn.fragella.com/images/tom-ford-ombre-leather.jpg','Tom Ford Ombre Leather',2018,'Strong','Ombre Leather','A woody, powdery, smoky composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(19,'Tom Ford','Men','https://cdn.fragella.com/images/tom-ford-velvet-orchid.jpg','Tom Ford Velvet Orchid',2014,'Strong','Velvet Orchid','A floral, sweet, powdery composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(20,'Tom Ford','Men','https://cdn.fragella.com/images/tom-ford-oud-wood.jpg','Tom Ford Oud Wood',2007,'Moderate','Oud Wood','A oriental, spicy, warm composition by Tom Ford. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]'),
(21,'Versace','women','https://cdn.fragella.com/images/gianni-versace-versace-for-women.jpg','Gianni Versace for women',1981,'Strong','Gianni Versace','A fresh, citrus, aromatic composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]'),
(22,'Versace','men','https://cdn.fragella.com/images/versace-man-versace-for-men.jpg','Versace Man for men',2003,'Strong','Man','A fresh, citrus, aromatic composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]'),
(23,'Versace','women','https://cdn.fragella.com/images/versace-woman-summer-versace-for-women.jpg','Versace Woman Summer for women',2002,'Moderate','Woman Summer','A fresh, citrus, aromatic composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]'),
(24,'Versace','women','https://cdn.fragella.com/images/versace-essence-ethereal-versace-for-women.jpg','Versace Essence Ethereal for women',2000,'Moderate','Essence Ethereal','A fresh, citrus, aromatic composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]'),
(25,'Versace','women','https://cdn.fragella.com/images/versace-essence-emotional-versace-for-women.jpg','Versace Essence Emotional for women',2000,'Moderate','Essence Emotional','A sweet, gourmand, vanilla composition by Versace. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Mandarin","Blackcurrant"],"middle":["Honey","Orange Blossom","Jasmine"],"base":["Vanilla","Tonka Bean","Patchouli"]}','["Sweet","Gourmand","Vanilla","Amber"]'),
(26,'Giorgio Armani','men','https://cdn.fragella.com/images/giorgio-armani-variety.jpg','Giorgio Armani Variety',2004,'Strong','Variety','A woody, powdery, smoky composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(27,'Giorgio Armani','women','https://cdn.fragella.com/images/armani-giorgio-armani-for-women.jpg','Armani for women',1981,'Strong','Signature','A woody, powdery, smoky composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(28,'Giorgio Armani','men','https://cdn.fragella.com/images/armani-attitude-giorgio-armani-for-men.jpg','Armani Attitude for men',2007,'Moderate','Armani Attitude','A woody, powdery, smoky composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(29,'Giorgio Armani','unisex','https://cdn.fragella.com/images/armani-prive-laque-giorgio-armani-unisex.jpg','Armani Prive Laque unisex',2019,'Strong','Armani Prive','A woody, powdery, smoky composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(30,'Giorgio Armani','men','https://cdn.fragella.com/images/armani-mania-giorgio-armani-for-men.jpg','Armani Mania for men',2002,'Moderate','Armani Mania','A oriental, spicy, warm composition by Giorgio Armani. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]'),
(31,'Creed','women','https://cdn.fragella.com/images/creed.jpg','Creed',2010,'Moderate','Signature','A woody, powdery, smoky composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(32,'Creed','unisex','https://cdn.fragella.com/images/creed-pour-enfants-creed-unisex.jpg','Creed Pour Enfants unisex',2015,'Moderate','Pour Enfants','A woody, powdery, smoky composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(33,'Creed','men','https://cdn.fragella.com/images/creed-viking.jpg','Creed Viking',2017,'Moderate','Viking','A woody, powdery, smoky composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(34,'Creed','men','https://cdn.fragella.com/images/creed-erolfa.jpg','Creed Erolfa',1992,'Moderate','Erolfa','A fresh, citrus, aromatic composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]'),
(35,'Creed','men','https://cdn.fragella.com/images/creed-himalaya.jpg','Creed Himalaya',2002,'Moderate','Himalaya','A fresh, citrus, aromatic composition by Creed. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]'),
(36,'Jean Paul Gaultier','unisex','https://cdn.fragella.com/images/gaultier2-jean-paul-gaultier-unisex.jpg','Gaultier2 unisex',2022,'Moderate','Signature','A woody, powdery, smoky composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(37,'Jean Paul Gaultier','men','https://cdn.fragella.com/images/jean-paul-gaultier.jpg','Jean Paul Gaultier',1995,'Strong','Jean Paul','A woody, powdery, smoky composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(38,'Jean Paul Gaultier','women','https://cdn.fragella.com/images/jean-paul-gaultier-summer-jean-paul-gaultier-for-women.jpg','Jean Paul Gaultier Summer for women',1997,'Strong','Summer','A fresh, citrus, aromatic composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Lemon","Grapefruit"],"middle":["Lavender","Mint","Neroli"],"base":["Vetiver","White Musk","Amberwood"]}','["Fresh","Citrus","Aromatic","Green"]'),
(39,'Jean Paul Gaultier','women','https://cdn.fragella.com/images/jean-paul-gaultier-divine.jpg','Jean Paul Gaultier Divine',2023,'Moderate','Divine','A floral, sweet, powdery composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(40,'Jean Paul Gaultier','women','https://cdn.fragella.com/images/jean-paul-gaultier-scandal.jpg','Jean Paul Gaultier Scandal',2017,'Strong','Scandal','A oriental, spicy, warm composition by Jean Paul Gaultier. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]'),
(41,'Prada','men','https://cdn.fragella.com/images/prada.jpg','Prada',2004,'Strong','Signature','A woody, powdery, smoky composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(42,'Prada','women','https://cdn.fragella.com/images/prada-prada-for-women.jpg','Prada Prada for women',1990,'Strong','Prada','A woody, powdery, smoky composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Bergamot","Pink Pepper"],"middle":["Iris Pallida","Violet Leaf","Suede"],"base":["Vetiver","Smoked Cedar","Ambrette"]}','["Woody","Powdery","Smoky","Leather"]'),
(43,'Prada','women','https://cdn.fragella.com/images/prada-tendre-prada-for-women.jpg','Prada Tendre for women',2006,'Strong','Tendre','A floral, sweet, powdery composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]'),
(44,'Prada','women','https://cdn.fragella.com/images/prada-intense-prada-for-women.jpg','Prada Intense for women',2005,'Strong','Intense','A oriental, spicy, warm composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Cardamom","Saffron","Ginger"],"middle":["Rose","Cinnamon","Oud"],"base":["Amber","Vanilla","Benzoin"]}','["Oriental","Spicy","Warm","Amber"]'),
(45,'Prada','women','https://cdn.fragella.com/images/prada-les-infusion-de-prada.jpg','Prada Les Infusion De Prada',2022,'Moderate','Les Infusion De Prada','A floral, sweet, powdery composition by Prada. Elegant opening, refined heart, and a memorable dry-down.','{"top":["Pear","Pink Pepper"],"middle":["Rose","Jasmine","Peony"],"base":["Musk","Cedar","Vanilla"]}','["Floral","Sweet","Powdery","Fruity"]');
/*!40000 ALTER TABLE `perfume` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
